# This file should be placed in your Git repository for the 'prod' profile
app.greeting=Hello from Prod Environment!
app.description=This is the production environment configuration
app.feature.enabled=true