
# This file should be placed in your Git repository
app.greeting=[Updated] Hello from Config Server!
app.description=This property is loaded from the Config Server

app.secret={cipher}2b4ec980bf0365c78ca22adeaea9964c831174ca58dcf8ded077e5fe5a4e1075