
# This file should be placed in your Git repository
app.greeting=Hello from Config Server!
app.description=This property is loaded from the Config Server

app.secret={cipher}b3a985ac713fce40b7a7ad89eae0ee78047bc09b65b9ec568c34e762097ee7f6